CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    picture_url TEXT
);

CREATE TABLE product_info (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255)
);

CREATE TABLE orders_date (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255) NOT NULL,
    date_created DATE DEFAULT CURRENT_DATE
);

CREATE TABLE order_product (
    quantity INT NOT NULL CHECK (quantity > 0),
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);